using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Dan Purcell 8/10/15 
*/

namespace Euler12
{
    class Program
    {
        static void Main(string[] args)
        {
            int n = 1;
            long j = 1;

            bool go = true;

            int best = 0;

            while (go)
            {                
                int divs = 0;
                
                for (int i = 1; i < (j/2) + 1; i++)
                {

                    if (j % i == 0)
                        divs++;

                    if (divs > 500)
                    {
                        Console.WriteLine(j + ":" + divs);
                        go = false;
                        break;
                    }
                }
                if (divs > best)
                {
                    Console.WriteLine(j + ":" + divs);
                    best = divs;
                }
                n++;
                j += n;
            }
            Console.ReadKey();
        }
    }
}
